### ISSUE TITLE
Bootstrap coredns/keepalived files need additional documentation

### ISSUE THREAD

**Issue by stbenjam** [metalkube/kni-installer#144]
A number of files in  data/data/bootstrap/baremetal contain the configuration for coredns and keepalived.  The installer team has asked us to document the purpose of each file, could we add comments to each one explaining it's purpose?

**Comment by stbenjam** [comment]
See: https://github.com/openshift/installer/pull/1873#issuecomment-509697686

**Comment by russellb** [comment]
I've started a branch to try to document the bootstrap VM assets here: https://github.com/russellb/kni-installer/commits/baremetal-net-docs

**Comment by russellb** [comment]
I just saw #146 as well.  It looks like what I've started is complementary, though.  @cybertron

**Comment by stbenjam** [comment]
Have we added all the docs we want for this now?

**Comment by russellb** [comment]
Yes, I think we can call this complete
