### ISSUE TITLE
installer should register hosts for masters and workers

### ISSUE THREAD

**Issue by dhellmann** [metalkube/kni-installer#46]
# Platform (aws|libvirt|openstack):

baremetal

# What happened?

After the cluster was running, there were no BareMetalHost objects associated with the Machines for master Nodes.

# What you expected to happen?

At least the information for the BareMetalHost CRs for the masters should be registered. If those are set up with the machineRef linked to existing Machines, the hosts will be marked as "externally provisioned" and managed more safely (they won't be rebooted to inspect their hardware).

# How to reproduce it (as minimally and precisely as possible)?

```console
$ cd dev-scripts
$ make
```

# Anything else we need to know?

To populate the hardware details for masters we will have to update the Status block of the host objects.

# References

- https://github.com/openshift-metalkube/dev-scripts/pull/330

**Comment by russellb** [comment]
This should be expanded to include the BareMetalHosts for workers if more than 3 hosts were provided to the installer.  This is needed so we can deploy masters + workers in one shot.

**Comment by hardys** [comment]
In addition to registering the hosts we should wait for them to become ready, as currently we exit the installer early compared to other platforms

**Comment by russellb** [comment]
moved here: https://github.com/openshift/installer/issues/2063
