### ISSUE TITLE
VM host with short hostname will cause master VMs to fail to start and terraform to abort

### ISSUE THREAD

**Issue by dustinblack** [metalkube/kni-installer#48]
# Version

kni-install from source via openshift-metalkube/dev-scripts

# Platform (aws|libvirt|openstack):

libvirt emulating baremetal via openshift-metalkube

# What happened?

Terraform bailed out with nondescript "internal server error" messages.

See [http://people.redhat.com/dblack/06_create_cluster-2019-04-16-171211.log]

# What you expected to happen?

Well, not that ^^

The terraform process should have completed.

# How to reproduce it (as minimally and precisely as possible)?

As of 2019-04-16, run an openshift-metalkube dev-scripts install on a CentOS 7 node with libvirtd and a short (non-FQDN) hostname.

```console
hostnamectl set-hostname narf
nostnamectl set-hostname narf --transient
git clone https://github.com/openshift-metalkube/dev-scripts.git
cd dev-scripts
make
```

**Comment by markmc** [comment]
@stbenjam any idea what's going on here?

**Comment by stbenjam** [comment]
Ironic is returning 500, only real way to find out why is look at the Ironic pod logs, @dustinblack  could you share:

```console
podman exec ironic cat /shared/log/ironic/ironic-conductor.log
podman exec ironic cat /shared/log/ironic/ironic-api.log
```

**Comment by stbenjam** [comment]
Please re-open this against the baremetal platform in the openshift/installer repo if you encounter this again, and can provide the Ironic logs. Thanks!
