### ISSUE TITLE
Remove early exit from installer

### ISSUE THREAD

**Issue by stbenjam** [metalkube/kni-installer#60]
Currently we exit early from the installer, and do a bunch of hacks in 06_create_cluster.sh.

- [x] Remove the NoSchedule taint from masters
    - PR: ~~https://github.com/openshift/machine-config-operator/pull/846~~ Merged
    - Can remove on next rebase

- [x] Remove patch_ep_host_etcd
    - PR: https://github.com/openshift-metal3/dev-scripts/pull/620

- [X] ~~Remove csr signing https://github.com/openshift-metal3/dev-scripts/issues/260~~
  - Alternative merged: moved csr signing before running installer https://github.com/openshift-metal3/dev-scripts/pull/621

- [x] Remove add-machine-ips.sh script https://github.com/openshift-metal3/dev-scripts/blob/master/06_create_cluster.sh#L85-L94

**Comment by russellb** [comment]
One complication here is that we don't want this done in *every* case of the baremetal platform.

We don't have a declarative way to specify this right now.  Once it's configurable somewhere, this might be a customization that happens at the "create manifests" stage, or remain as a day 2 operation.

If we want to re-phrase this issue as "remove early exit", there's another path to doing that.  

* First we need to register BareMeralHosts for masters: https://github.com/openshift-metal3/kni-installer/issues/46
* We also need to register 1 or more BareMetalHosts that can be provisioned as workers

With that in place, the installer can provision a cluster, including a worker, that should run to completion.

Making workloads run on masters is still required if we only have 3 hosts to deploy to, though.

**Comment by stbenjam** [comment]
@dhellmann and I were talking about this last week, for the installer to be able to register BareMetalHosts,  we would need the CRD in the installer, and there was pushback about that from the installer team.  Did we come to any conclusions about how to handle it?

**Comment by dhellmann** [comment]
> @dhellmann and I were talking about this last week, for the installer to be able to register BareMetalHosts, we would need the CRD in the installer, and there was pushback about that from the installer team. Did we come to any conclusions about how to handle it?

Not yet. I'm going to look further into how the installer ensures the CRDs for the cluster-api resources like Machine are registered to see if we can add the metal3 resources there.

**Comment by stbenjam** [comment]
I opened a PR here - https://github.com/openshift/machine-config-operator/pull/722, since we already added baremetal to openshift/api, I think it makes sense to add ourselves to MCO before we open the installer PR's.  We'll need that regardless.

That does include removing the NoSchedule taint.  Given how powerful the metal running the control plane is, seems like a waste of machines to not want that by default.  Maybe we could do something with the templating in MCO to make it configurable some how.  The only other option is https://github.com/openshift/installer/blob/master/docs/user/customization.md#install-time-customization-for-machine-configuration, which gets into dev-scripts hackiness again.

**Comment by stbenjam** [comment]
I re-opened the MCO PR, https://github.com/openshift/machine-config-operator/pull/846, to remove the no schedule taints.  Until workers are being deployed with the installer, this is required because ingress, monitoring, and registry operators otherwise won't come up.  We can remove the kubelet override once that happens, but I don't want to block opening the openshift/installer PR on waiting for that.

**Comment by markmc** [comment]
It looks like we're mostly just waiting on a replacement for add-machine-ips.sh ?

I see progress on e.g. metal3-io/cluster-api-provider-baremetal#49 but it's a struggle to piece it all together into a coherent summary of status on this ...

**Comment by russellb** [comment]
I don’t think we need early exit for that. It can be moved to post install. The purpose of that is to enable auto approval of CSRs, which the cron job handles in the meantime. 

For a more detailed history of the CSR issue, see https://github.com/openshift-metal3/dev-scripts/issues/260

I need to check back into this. I think we may have enough finished that everything works normally for workers. We lack introspection data on the BareMetalHost objects for masters. That data is needed so the actuator can copy it over to the Machine.
