### ISSUE TITLE
Turn SELinux back on in bootstrap VM

### ISSUE THREAD

**Issue by russellb** [metalkube/kni-installer#63]
The following commit turned off SELinux on the bootstrap VM: https://github.com/openshift-metal3/kni-installer/commit/69236afe4d

We need to debug whatever SELinux issues remain and turn this back on.

**Comment by stbenjam** [comment]
This was added when we were troubleshooting the ootpa upgrade woes.  We removed this from the dev-scripts -> https://github.com/openshift-metal3/dev-scripts/pull/300, I presume it can be removed from kni-installer, will test.
