### ISSUE TITLE
Undo rename to kni-installer

### ISSUE THREAD

**Issue by russellb** [metalkube/kni-installer#66]
We renamed the fork to kni-installer and updated all of the go import paths to reflect this.  This needs to be undone before we can submit a PR back to openshift/installer.

We can retain this fork, but I imagine a typical env will clone openshift/installer, and then add our fork as a branch, leaving the repo under github.com/openshift/installer in their gopath.

**Comment by stbenjam** [comment]
I undid the rename on a personal [branch](https://github.com/openshift/installer/compare/master...stbenjam:bare-metal#files_bucket) using this:

```console
$ sed -i 's|openshift-metalkube/kni-installer|openshift/installer|g' $(git grep -l openshift-metalkube/kni-installer | grep '\(cmd\|build.sh\|pkg\|assets_generate.go\)')
$ sed -i 's|kni-install|openshift-install|g' $(git grep -l kni-install | grep '\(cmd\|build.sh\|pkg\)')
$ git mv cmd/kni-install cmd/openshift-install
```

What do you think of keeping a branch here with an un-renamed copy of master? For easy comparision with openshift/installer.

**Comment by russellb** [comment]
Is a branch really necessary, though?  Can we just make these changes directly in master?

**Comment by stbenjam** [comment]
Oh, I see - should do, if we move it to `$GOPATH/src/github.com/openshift/installer` everywhere it gets used, otherwise go will be unhappy

**Comment by markmc** [comment]
I made the first patch on the rebasing branch take care of the renaming, so we can easily ignore the noise of the renaming

But maybe we could rename openshift-metalkube/kni-installer to openshift-metalkube/installer and make it so that the only way you build it is like:

```
go get -d github.com/openshift/installer
cd ~/go/src/github.com/openshift/installer
git remote add -f kni git@github.com:openshift-metalkube/installer.git
git checkout -b kni kni/master
```

i.e. you have to build it as a standard branch of openshfit-install

**Comment by stbenjam** [comment]
I think we can just close this, I have a branch here https://github.com/openshift-metal3/installer/pull/1 with the undone rename, which is trivial to redo as needed.
