### ISSUE TITLE
Automatically launch Ironic within the bootstrap VM to provision masters

### ISSUE THREAD

**Issue by russellb** [metalkube/kni-installer#68]
kni-install currently assumes Ironic has been stood up outside of the installer.  Terraform will drive that instance of Ironic to provision the masters.

Instead, we'd like to be able to minimize external pre-requisites and be able to spin up Ironic within the bootstrap VM for provisioning the masters.

Either way, this instance of Ironic is supposed to be temporary.  Once the cluster comes up, the baremetal-operator should be managing Ironic within the cluster.

**Comment by stbenjam** [comment]
It occurs to me that we launch the masters and bootstrap concurrently.  We'll need a mechanism to have Terraform wait for Ironic to be available on the bootstrap node before trying to create any baremetal resources.

The solution to this seems to be using [depends_on](https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies), to have each individual Ironic resource wait for something.  It can't be used at the module level, but [this workaround](https://github.com/hashicorp/terraform/issues/10462#issuecomment-285733504) may work for us.

We'd then use a [local-exec provisioner](https://www.terraform.io/docs/provisioners/local-exec.html) on the bootstrap resource we're waiting for to poll until Ironic API is up.

**Comment by hardys** [comment]
Moved tracking of this to https://github.com/openshift/installer/issues/2060
