### ISSUE TITLE
Remove openstack terminology

### ISSUE THREAD

**Issue by stbenjam** [metalkube/kni-installer#70]
The bootstrap VM's terraform config refers to the "overcloud" bridge. IMHO this should be renamed to something less attached to OpenStack tripleo.

```hcl
variable "overcloud_bridge" {
  type        = "string"
  description = "The name of the overcloud bridge"
}
```

**Comment by hardys** [comment]
Sounds good - FYI I've pushed https://github.com/openshift-metal3/dev-scripts/pull/500 where I rename all "overcloud" things to just "vm"
