### ISSUE TITLE
Upgrade to terraform 0.12

### ISSUE THREAD

**Issue by stbenjam** [metalkube/kni-installer#78]
See: https://github.com/openshift/installer/pull/1739

openshift/installer is moving to terraform 0.12.  We'll need to account for these changes in our HCL, with 0.12's new features we can probably make it look nicer, including having a better data structure (see https://github.com/openshift-metal3/kni-installer/issues/57)  in the baremetal platform's install-config.

**Comment by hardys** [comment]
This is good news :)

**Comment by stbenjam** [comment]
This is done! 4.2 rebase upgraded us to 0.12.

https://github.com/openshift-metal3/kni-installer/pull/91
