### ISSUE TITLE
Provide the BareMetalMachineProviderSpec with the right fields 

### ISSUE THREAD

**Issue by sadasu** [metalkube/kni-installer#87]

**Comment by russellb** [comment]
As of #85 , kni-install will create the master Machines and worker MachineSet with the baremetal machine providerSpec.  The next step is to populate the contents that `cluster-api-provider-baremetal` expects.

There are two fields that must get set in our case: the image and userdata.

Prior to having the baremetal machine providerSpec, cluster-api-provider-baremetal had the image location and the image checksum location hard coded.  It will now expect to receive this in the providerSpec.  It looks like the image URL is already in the install-config.yaml.  The checksum is passed in as a value vs. the URL, so we may have to add a URL to the checksum as another part of the install config.  See https://github.com/openshift-metal3/kni-installer/issues/57 for a discussion of the current install-config contents.

The other is the userdata field.  Prior to this change, cluster-api-provider-baremetal assumed there would be a Secret named `worker-user-data`.  Now it should come from the providerSpec.  The installer probably knows the right name to use.

See https://github.com/metal3-io/cluster-api-provider-baremetal/pull/59 for where some of this hard coded information was removed.

See https://github.com/metal3-io/cluster-api-provider-baremetal/blob/master/docs/api.md for more documentation on the baremetal machine providerspec.

**Comment by russellb** [comment]
It looks like the name of the user-data secret is already passed in as an argument: https://github.com/openshift-metal3/kni-installer/blob/master/pkg/asset/machines/master.go#L166
